---

- hosts: all
  become: true
  tasks:

# code
  - name: install apache, php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache, php package
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"
 
# need to add the equivalent of 
# sudo systemctl start httpd
# sudo firewall-cmd --add-port=80/tcp
