---

- hosts: all
  become: true
  tasks:

# code
  - name: install apache, php package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
 
# need to add the equivalent of 
# sudo systemctl start httpd
# sudo firewall-cmd --add-port=80/tcp
